// Generated by gencpp from file pick_delivery/c_to_s.msg
// DO NOT EDIT!


#ifndef PICK_DELIVERY_MESSAGE_C_TO_S_H
#define PICK_DELIVERY_MESSAGE_C_TO_S_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_delivery
{
template <class ContainerAllocator>
struct c_to_s_
{
  typedef c_to_s_<ContainerAllocator> Type;

  c_to_s_()
    : sender()
    , receiver()
    , auladest()  {
    }
  c_to_s_(const ContainerAllocator& _alloc)
    : sender(_alloc)
    , receiver(_alloc)
    , auladest(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sender_type;
  _sender_type sender;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _receiver_type;
  _receiver_type receiver;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _auladest_type;
  _auladest_type auladest;





  typedef boost::shared_ptr< ::pick_delivery::c_to_s_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_delivery::c_to_s_<ContainerAllocator> const> ConstPtr;

}; // struct c_to_s_

typedef ::pick_delivery::c_to_s_<std::allocator<void> > c_to_s;

typedef boost::shared_ptr< ::pick_delivery::c_to_s > c_to_sPtr;
typedef boost::shared_ptr< ::pick_delivery::c_to_s const> c_to_sConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_delivery::c_to_s_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_delivery::c_to_s_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_delivery::c_to_s_<ContainerAllocator1> & lhs, const ::pick_delivery::c_to_s_<ContainerAllocator2> & rhs)
{
  return lhs.sender == rhs.sender &&
    lhs.receiver == rhs.receiver &&
    lhs.auladest == rhs.auladest;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_delivery::c_to_s_<ContainerAllocator1> & lhs, const ::pick_delivery::c_to_s_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::c_to_s_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::c_to_s_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::c_to_s_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::c_to_s_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::c_to_s_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::c_to_s_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_delivery::c_to_s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1edfb1960ffea85e363609983abdaaf3";
  }

  static const char* value(const ::pick_delivery::c_to_s_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1edfb1960ffea85eULL;
  static const uint64_t static_value2 = 0x363609983abdaaf3ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_delivery::c_to_s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_delivery/c_to_s";
  }

  static const char* value(const ::pick_delivery::c_to_s_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_delivery::c_to_s_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender\n"
"string receiver\n"
"string auladest\n"
;
  }

  static const char* value(const ::pick_delivery::c_to_s_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_delivery::c_to_s_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender);
      stream.next(m.receiver);
      stream.next(m.auladest);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct c_to_s_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_delivery::c_to_s_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_delivery::c_to_s_<ContainerAllocator>& v)
  {
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sender);
    s << indent << "receiver: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.receiver);
    s << indent << "auladest: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.auladest);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_DELIVERY_MESSAGE_C_TO_S_H
