// Generated by gencpp from file pick_delivery/s_to_c.msg
// DO NOT EDIT!


#ifndef PICK_DELIVERY_MESSAGE_S_TO_C_H
#define PICK_DELIVERY_MESSAGE_S_TO_C_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_delivery
{
template <class ContainerAllocator>
struct s_to_c_
{
  typedef s_to_c_<ContainerAllocator> Type;

  s_to_c_()
    : msgs()  {
    }
  s_to_c_(const ContainerAllocator& _alloc)
    : msgs(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msgs_type;
  _msgs_type msgs;





  typedef boost::shared_ptr< ::pick_delivery::s_to_c_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_delivery::s_to_c_<ContainerAllocator> const> ConstPtr;

}; // struct s_to_c_

typedef ::pick_delivery::s_to_c_<std::allocator<void> > s_to_c;

typedef boost::shared_ptr< ::pick_delivery::s_to_c > s_to_cPtr;
typedef boost::shared_ptr< ::pick_delivery::s_to_c const> s_to_cConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_delivery::s_to_c_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_delivery::s_to_c_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_delivery::s_to_c_<ContainerAllocator1> & lhs, const ::pick_delivery::s_to_c_<ContainerAllocator2> & rhs)
{
  return lhs.msgs == rhs.msgs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_delivery::s_to_c_<ContainerAllocator1> & lhs, const ::pick_delivery::s_to_c_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::s_to_c_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::s_to_c_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::s_to_c_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::s_to_c_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::s_to_c_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::s_to_c_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_delivery::s_to_c_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d8e418f1fcd36e8930c91006766237d";
  }

  static const char* value(const ::pick_delivery::s_to_c_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d8e418f1fcd36e8ULL;
  static const uint64_t static_value2 = 0x930c91006766237dULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_delivery::s_to_c_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_delivery/s_to_c";
  }

  static const char* value(const ::pick_delivery::s_to_c_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_delivery::s_to_c_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msgs\n"
;
  }

  static const char* value(const ::pick_delivery::s_to_c_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_delivery::s_to_c_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msgs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct s_to_c_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_delivery::s_to_c_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_delivery::s_to_c_<ContainerAllocator>& v)
  {
    s << indent << "msgs: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msgs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_DELIVERY_MESSAGE_S_TO_C_H
